/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\AAA\\other\\vue\\uestcLC\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-52c3cdf8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52c3cdf8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-97389c24",
    path: "/detaildocs/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97389c24").then(next)
    },
  },
  {
    path: "/detaildocs/guide/index.html",
    redirect: "/detaildocs/guide/"
  },
  {
    name: "v-27836644",
    path: "/detaildocs/char/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27836644").then(next)
    },
  },
  {
    path: "/detaildocs/char/index.html",
    redirect: "/detaildocs/char/"
  },
  {
    name: "v-5ec205ae",
    path: "/detaildocs/plot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ec205ae").then(next)
    },
  },
  {
    path: "/detaildocs/plot/index.html",
    redirect: "/detaildocs/plot/"
  },
  {
    name: "v-7997966e",
    path: "/detaildocs/monster/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7997966e").then(next)
    },
  },
  {
    path: "/detaildocs/monster/index.html",
    redirect: "/detaildocs/monster/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]