/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "铠甲勇士",
  "description": "ARMOR HERO",
  "base": "/uestcLC/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "铠甲勇士",
        "tagline": "ARMOR HERO",
        "actionText": "进入主页",
        "actionLink": "detaildocs/guide/",
        "features": [
          {
            "title": null
          },
          {
            "title": "铠甲勇士",
            "details": "宇宙生命永不会停息，相信自己的身体总带着潜在的能力，改变总将带来成长的惊喜，万丈光芒照耀一个崭新的天地，善恶就存在我们的身边，当你遇到困难的时候，第一想到的就要奋战到底，要在恶念打击之前，拿出你最大的能力反击，最后的胜利属于勇敢的自己，One two three four five go，炎龙侠升腾炎上就是焰火的力量，无限就是火之炎龙铠甲，风鹰侠曲直屈伸就是巨木的力量，说时迟那时快，召唤木之风鹰铠甲，黑犀侠滋润掩藏但发出狂啸的力量，召唤水之黑犀铠甲，雪獒侠他有能刚能柔之金的力量，还有地虎侠他要召唤土之地虎铠甲，退缩是永远说不出的两字，投降是还不愿意学的姿势，追击不容敌人一丝丝喘息，胜利就再给邪恶迎头痛击，我们是光的英雄，我们是铠甲勇士，我们是影的克星，我们是铠甲勇士，合体铠甲我面对迎击，我们是光的英雄，合体铠甲我穿梭光影，我们是光的勇士，为正义我一定胜利，我们是铠甲勇士，无论如何一定要赢，我们是我们是铠甲勇士"
          },
          {
            "title": null
          }
        ],
        "footer": "制作人：六柒八玖丶----------仅供学习，不可用于商业用途"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-52c3cdf8",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/detaildocs/guide/",
      "relativePath": "detaildocs/guide/README.md",
      "key": "v-97389c24",
      "path": "/detaildocs/guide/",
      "headers": [
        {
          "level": 2,
          "title": "剧情介绍",
          "slug": "剧情介绍"
        },
        {
          "level": 3,
          "title": "简略剧情",
          "slug": "简略剧情"
        },
        {
          "level": 3,
          "title": "详细剧情",
          "slug": "详细剧情"
        },
        {
          "level": 2,
          "title": "人物及铠甲介绍",
          "slug": "人物及铠甲介绍"
        },
        {
          "level": 3,
          "title": "人物",
          "slug": "人物"
        },
        {
          "level": 3,
          "title": "铠甲",
          "slug": "铠甲"
        },
        {
          "level": 2,
          "title": "异能兽介绍",
          "slug": "异能兽介绍"
        }
      ]
    },
    {
      "title": "人物及铠甲介绍",
      "frontmatter": {},
      "regularPath": "/detaildocs/char/",
      "relativePath": "detaildocs/char/README.md",
      "key": "v-27836644",
      "path": "/detaildocs/char/",
      "headers": [
        {
          "level": 2,
          "title": "角色介绍",
          "slug": "角色介绍"
        },
        {
          "level": 3,
          "title": "李炘南",
          "slug": "李炘南"
        },
        {
          "level": 3,
          "title": "东杉",
          "slug": "东杉"
        },
        {
          "level": 3,
          "title": "北淼",
          "slug": "北淼"
        },
        {
          "level": 3,
          "title": "坤中",
          "slug": "坤中"
        },
        {
          "level": 3,
          "title": "西钊",
          "slug": "西钊"
        },
        {
          "level": 3,
          "title": "美真",
          "slug": "美真"
        },
        {
          "level": 3,
          "title": "徐敏慈",
          "slug": "徐敏慈"
        },
        {
          "level": 3,
          "title": "小雪（冰儿）",
          "slug": "小雪-冰儿"
        },
        {
          "level": 3,
          "title": "蕙姨",
          "slug": "蕙姨"
        },
        {
          "level": 3,
          "title": "殿南",
          "slug": "殿南"
        },
        {
          "level": 3,
          "title": "方中",
          "slug": "方中"
        },
        {
          "level": 3,
          "title": "北凯",
          "slug": "北凯"
        },
        {
          "level": 3,
          "title": "泽西",
          "slug": "泽西"
        },
        {
          "level": 3,
          "title": "文东",
          "slug": "文东"
        },
        {
          "level": 3,
          "title": "小嵩",
          "slug": "小嵩"
        },
        {
          "level": 3,
          "title": "王向阳",
          "slug": "王向阳"
        },
        {
          "level": 3,
          "title": "丑将",
          "slug": "丑将"
        },
        {
          "level": 3,
          "title": "张健",
          "slug": "张健"
        },
        {
          "level": 3,
          "title": "影霸",
          "slug": "影霸"
        },
        {
          "level": 3,
          "title": "卡伦（界王）",
          "slug": "卡伦-界王"
        },
        {
          "level": 3,
          "title": "黑帝",
          "slug": "黑帝"
        },
        {
          "level": 2,
          "title": "铠甲介绍",
          "slug": "铠甲介绍"
        },
        {
          "level": 3,
          "title": "炎龙铠甲",
          "slug": "炎龙铠甲"
        },
        {
          "level": 3,
          "title": "风鹰铠甲",
          "slug": "风鹰铠甲"
        },
        {
          "level": 3,
          "title": "黑犀铠甲",
          "slug": "黑犀铠甲"
        },
        {
          "level": 3,
          "title": "地虎铠甲",
          "slug": "地虎铠甲"
        },
        {
          "level": 3,
          "title": "雪獒铠甲",
          "slug": "雪獒铠甲"
        },
        {
          "level": 3,
          "title": "帝皇铠甲",
          "slug": "帝皇铠甲"
        },
        {
          "level": 2,
          "title": "装备",
          "slug": "装备"
        },
        {
          "level": 3,
          "title": "铠甲召唤器",
          "slug": "铠甲召唤器"
        },
        {
          "level": 3,
          "title": "乾坤腰带",
          "slug": "乾坤腰带"
        },
        {
          "level": 3,
          "title": "禅定印",
          "slug": "禅定印"
        },
        {
          "level": 3,
          "title": "光影驹",
          "slug": "光影驹"
        },
        {
          "level": 2,
          "title": "影界",
          "slug": "影界"
        },
        {
          "level": 3,
          "title": "影霸",
          "slug": "影霸-2"
        },
        {
          "level": 3,
          "title": "丑将",
          "slug": "丑将-2"
        },
        {
          "level": 3,
          "title": "界王",
          "slug": "界王"
        },
        {
          "level": 3,
          "title": "西钊（脱离）",
          "slug": "西钊-脱离"
        },
        {
          "level": 3,
          "title": "冰儿（脱离）",
          "slug": "冰儿-脱离"
        },
        {
          "level": 3,
          "title": "胖头男",
          "slug": "胖头男"
        },
        {
          "level": 3,
          "title": "阿豆",
          "slug": "阿豆"
        },
        {
          "level": 3,
          "title": "嘻哈男",
          "slug": "嘻哈男"
        },
        {
          "level": 3,
          "title": "张健（脱离）",
          "slug": "张健-脱离"
        },
        {
          "level": 3,
          "title": "黑帝",
          "slug": "黑帝-2"
        },
        {
          "level": 3,
          "title": "巴豆",
          "slug": "巴豆"
        }
      ]
    },
    {
      "title": "详细剧情介绍",
      "frontmatter": {},
      "regularPath": "/detaildocs/plot/",
      "relativePath": "detaildocs/plot/README.md",
      "key": "v-5ec205ae",
      "path": "/detaildocs/plot/",
      "headers": [
        {
          "level": 2,
          "title": "详细剧情",
          "slug": "详细剧情"
        },
        {
          "level": 3,
          "title": "第1集 异能兽入侵",
          "slug": "第1集-异能兽入侵"
        },
        {
          "level": 3,
          "title": "第2集 炎龙现身",
          "slug": "第2集-炎龙现身"
        },
        {
          "level": 3,
          "title": "第3集 逃跑的蚱蜢兽",
          "slug": "第3集-逃跑的蚱蜢兽"
        },
        {
          "level": 3,
          "title": "第4集 神秘失踪的马匹",
          "slug": "第4集-神秘失踪的马匹"
        },
        {
          "level": 3,
          "title": "第5集 奇怪的神山老人",
          "slug": "第5集-奇怪的神山老人"
        },
        {
          "level": 3,
          "title": "第6集 东杉：我是风鹰侠",
          "slug": "第6集-东杉-我是风鹰侠"
        },
        {
          "level": 3,
          "title": "第7集 新生的魔牛兽",
          "slug": "第7集-新生的魔牛兽"
        },
        {
          "level": 3,
          "title": "第8集 封印蚂蚁兽",
          "slug": "第8集-封印蚂蚁兽"
        },
        {
          "level": 3,
          "title": "第9集 光影后人的秘密",
          "slug": "第9集-光影后人的秘密"
        },
        {
          "level": 3,
          "title": "第10集 出发，黑犀侠上",
          "slug": "第10集-出发-黑犀侠上"
        },
        {
          "level": 3,
          "title": "第11集 出发，黑犀侠下",
          "slug": "第11集-出发-黑犀侠下"
        },
        {
          "level": 3,
          "title": "第12集 大战恶狼兽上",
          "slug": "第12集-大战恶狼兽上"
        },
        {
          "level": 3,
          "title": "第13集 大战恶狼兽下",
          "slug": "第13集-大战恶狼兽下"
        },
        {
          "level": 3,
          "title": "第14集 土影石出世",
          "slug": "第14集-土影石出世"
        },
        {
          "level": 3,
          "title": "第15集 被夺走的土影石",
          "slug": "第15集-被夺走的土影石"
        },
        {
          "level": 3,
          "title": "第16集 寻找地虎侠",
          "slug": "第16集-寻找地虎侠"
        },
        {
          "level": 3,
          "title": "第17集 地虎侠现身",
          "slug": "第17集-地虎侠现身"
        },
        {
          "level": 3,
          "title": "第18集 水母兽的突袭",
          "slug": "第18集-水母兽的突袭"
        },
        {
          "level": 3,
          "title": "第19集 界王的追杀令",
          "slug": "第19集-界王的追杀令"
        },
        {
          "level": 3,
          "title": "第20集 界王的秘密",
          "slug": "第20集-界王的秘密"
        },
        {
          "level": 3,
          "title": "第21集 铠甲勇士，战斗吧",
          "slug": "第21集-铠甲勇士-战斗吧"
        },
        {
          "level": 3,
          "title": "第22集 恐怖的影界基地",
          "slug": "第22集-恐怖的影界基地"
        },
        {
          "level": 3,
          "title": "第23集 界王的圈套",
          "slug": "第23集-界王的圈套"
        },
        {
          "level": 3,
          "title": "第24集 被篡改的卫星密码",
          "slug": "第24集-被篡改的卫星密码"
        },
        {
          "level": 3,
          "title": "第25集 被挟持的卫星",
          "slug": "第25集-被挟持的卫星"
        },
        {
          "level": 3,
          "title": "第26集 进攻光影村",
          "slug": "第26集-进攻光影村"
        },
        {
          "level": 3,
          "title": "第27集 木之太极",
          "slug": "第27集-木之太极"
        },
        {
          "level": 3,
          "title": "第28集 光影传说",
          "slug": "第28集-光影传说"
        },
        {
          "level": 3,
          "title": "第29集 第五个铠甲勇士",
          "slug": "第29集-第五个铠甲勇士"
        },
        {
          "level": 3,
          "title": "第30集 界王的阴谋",
          "slug": "第30集-界王的阴谋"
        },
        {
          "level": 3,
          "title": "第31集 电磁风暴",
          "slug": "第31集-电磁风暴"
        },
        {
          "level": 3,
          "title": "第32集 大战游乐场",
          "slug": "第32集-大战游乐场"
        },
        {
          "level": 3,
          "title": "第33集 五行归位",
          "slug": "第33集-五行归位"
        },
        {
          "level": 3,
          "title": "第34集 摧毁！界王的老巢",
          "slug": "第34集-摧毁-界王的老巢"
        },
        {
          "level": 3,
          "title": "第35集 暗影四大天王",
          "slug": "第35集-暗影四大天王"
        },
        {
          "level": 3,
          "title": "第36集 暗影的反击",
          "slug": "第36集-暗影的反击"
        },
        {
          "level": 3,
          "title": "第37集 新炎龙侠登场",
          "slug": "第37集-新炎龙侠登场"
        },
        {
          "level": 3,
          "title": "第38集 黑暗五护法",
          "slug": "第38集-黑暗五护法"
        },
        {
          "level": 3,
          "title": "第39集 西钊的背叛",
          "slug": "第39集-西钊的背叛"
        },
        {
          "level": 3,
          "title": "第40集 坤中的指示",
          "slug": "第40集-坤中的指示"
        },
        {
          "level": 3,
          "title": "第41集 调查失火案",
          "slug": "第41集-调查失火案"
        },
        {
          "level": 3,
          "title": "第42集 复仇战",
          "slug": "第42集-复仇战"
        },
        {
          "level": 3,
          "title": "第43集 院长的信",
          "slug": "第43集-院长的信"
        },
        {
          "level": 3,
          "title": "第44集 争夺召唤权",
          "slug": "第44集-争夺召唤权"
        },
        {
          "level": 3,
          "title": "第45集 铠甲二队登场",
          "slug": "第45集-铠甲二队登场"
        },
        {
          "level": 3,
          "title": "第46集 争夺帝皇铠甲",
          "slug": "第46集-争夺帝皇铠甲"
        },
        {
          "level": 3,
          "title": "第47集 调查！帝皇铠甲的召唤",
          "slug": "第47集-调查-帝皇铠甲的召唤"
        },
        {
          "level": 3,
          "title": "第48集 终结黑暗五护法",
          "slug": "第48集-终结黑暗五护法"
        },
        {
          "level": 3,
          "title": "第49集 黑暗影帝登场",
          "slug": "第49集-黑暗影帝登场"
        },
        {
          "level": 3,
          "title": "第50集 苦斗！四大远古异能兽与帝皇侠",
          "slug": "第50集-苦斗-四大远古异能兽与帝皇侠"
        },
        {
          "level": 3,
          "title": "第51集 最终的战役",
          "slug": "第51集-最终的战役"
        },
        {
          "level": 3,
          "title": "第52集 结之真正含义",
          "slug": "第52集-结之真正含义"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/detaildocs/monster/",
      "relativePath": "detaildocs/monster/README.md",
      "key": "v-7997966e",
      "path": "/detaildocs/monster/",
      "headers": [
        {
          "level": 2,
          "title": "背景来源",
          "slug": "背景来源"
        },
        {
          "level": 3,
          "title": "第一部背景",
          "slug": "第一部背景"
        },
        {
          "level": 2,
          "title": "基本介绍",
          "slug": "基本介绍"
        },
        {
          "level": 3,
          "title": "影界基地",
          "slug": "影界基地"
        },
        {
          "level": 3,
          "title": "实际情况",
          "slug": "实际情况"
        },
        {
          "level": 2,
          "title": "战败后果",
          "slug": "战败后果"
        },
        {
          "level": 2,
          "title": "等级分类",
          "slug": "等级分类"
        },
        {
          "level": 3,
          "title": "暗影宝物",
          "slug": "暗影宝物"
        },
        {
          "level": 3,
          "title": "誓约锦囊",
          "slug": "誓约锦囊"
        },
        {
          "level": 3,
          "title": "最强神兵法器",
          "slug": "最强神兵法器"
        },
        {
          "level": 3,
          "title": "轮冥剑",
          "slug": "轮冥剑"
        },
        {
          "level": 2,
          "title": "低等异能兽",
          "slug": "低等异能兽"
        },
        {
          "level": 3,
          "title": "1号恶参兽",
          "slug": "_1号恶参兽"
        },
        {
          "level": 3,
          "title": "2号刺木兽",
          "slug": "_2号刺木兽"
        },
        {
          "level": 3,
          "title": "3号蚱蜢兽",
          "slug": "_3号蚱蜢兽"
        },
        {
          "level": 3,
          "title": "4号魔马兽",
          "slug": "_4号魔马兽"
        },
        {
          "level": 3,
          "title": "5号岩石兽",
          "slug": "_5号岩石兽"
        },
        {
          "level": 3,
          "title": "6号鳄鱼兽",
          "slug": "_6号鳄鱼兽"
        },
        {
          "level": 3,
          "title": "7号魔牛兽",
          "slug": "_7号魔牛兽"
        },
        {
          "level": 3,
          "title": "8号蚂蚁兽",
          "slug": "_8号蚂蚁兽"
        },
        {
          "level": 3,
          "title": "9号杏木兽",
          "slug": "_9号杏木兽"
        },
        {
          "level": 3,
          "title": "10号百合兽",
          "slug": "_10号百合兽"
        },
        {
          "level": 3,
          "title": "11号脓液兽",
          "slug": "_11号脓液兽"
        },
        {
          "level": 3,
          "title": "12号恶狼兽",
          "slug": "_12号恶狼兽"
        },
        {
          "level": 3,
          "title": "13号魔蚕兽",
          "slug": "_13号魔蚕兽"
        },
        {
          "level": 3,
          "title": "14号蜥蜴兽",
          "slug": "_14号蜥蜴兽"
        },
        {
          "level": 3,
          "title": "15号蛤蟆兽",
          "slug": "_15号蛤蟆兽"
        },
        {
          "level": 2,
          "title": "变种异能兽",
          "slug": "变种异能兽"
        },
        {
          "level": 3,
          "title": "16号水母兽（铠甲勇士机密档案的名字）",
          "slug": "_16号水母兽-铠甲勇士机密档案的名字"
        },
        {
          "level": 3,
          "title": "17号螳螂兽（铠甲勇士机密档案的名字）",
          "slug": "_17号螳螂兽-铠甲勇士机密档案的名字"
        },
        {
          "level": 3,
          "title": "18号魔羊兽",
          "slug": "_18号魔羊兽"
        },
        {
          "level": 3,
          "title": "19号魔鹿兽",
          "slug": "_19号魔鹿兽"
        },
        {
          "level": 3,
          "title": "20号苍蝇兽",
          "slug": "_20号苍蝇兽"
        },
        {
          "level": 3,
          "title": "21号蜘蛛兽",
          "slug": "_21号蜘蛛兽"
        },
        {
          "level": 3,
          "title": "22号恶蚊兽",
          "slug": "_22号恶蚊兽"
        },
        {
          "level": 3,
          "title": "23号蝎子兽",
          "slug": "_23号蝎子兽"
        },
        {
          "level": 3,
          "title": "24号蝴蝶兽",
          "slug": "_24号蝴蝶兽"
        },
        {
          "level": 3,
          "title": "25号黄蜂兽",
          "slug": "_25号黄蜂兽"
        },
        {
          "level": 3,
          "title": "26号龙虾兽",
          "slug": "_26号龙虾兽"
        },
        {
          "level": 3,
          "title": "27号蟑螂兽",
          "slug": "_27号蟑螂兽"
        },
        {
          "level": 3,
          "title": "28号天牛兽（铠甲勇士机密档案的名字）",
          "slug": "_28号天牛兽-铠甲勇士机密档案的名字"
        },
        {
          "level": 3,
          "title": "29号蜈蚣兽（铠甲勇士机密档案的名字）",
          "slug": "_29号蜈蚣兽-铠甲勇士机密档案的名字"
        },
        {
          "level": 3,
          "title": "30号乌贼兽",
          "slug": "_30号乌贼兽"
        },
        {
          "level": 3,
          "title": "31号海马兽",
          "slug": "_31号海马兽"
        },
        {
          "level": 3,
          "title": "32号海螺兽",
          "slug": "_32号海螺兽"
        },
        {
          "level": 3,
          "title": "33号飞蛾兽",
          "slug": "_33号飞蛾兽"
        },
        {
          "level": 3,
          "title": "34号魔蝉兽",
          "slug": "_34号魔蝉兽"
        },
        {
          "level": 3,
          "title": "35号界王兽",
          "slug": "_35号界王兽"
        },
        {
          "level": 2,
          "title": "细菌异能兽",
          "slug": "细菌异能兽"
        },
        {
          "level": 3,
          "title": "36号魔一",
          "slug": "_36号魔一"
        },
        {
          "level": 3,
          "title": "37号魔二",
          "slug": "_37号魔二"
        },
        {
          "level": 3,
          "title": "38号魔三",
          "slug": "_38号魔三"
        },
        {
          "level": 3,
          "title": "39号魔四",
          "slug": "_39号魔四"
        },
        {
          "level": 3,
          "title": "40号魔五",
          "slug": "_40号魔五"
        },
        {
          "level": 3,
          "title": "41号魔六",
          "slug": "_41号魔六"
        },
        {
          "level": 3,
          "title": "42号魔七",
          "slug": "_42号魔七"
        },
        {
          "level": 3,
          "title": "43号魔八",
          "slug": "_43号魔八"
        },
        {
          "level": 3,
          "title": "44号魔九",
          "slug": "_44号魔九"
        },
        {
          "level": 3,
          "title": "45号魔十",
          "slug": "_45号魔十"
        },
        {
          "level": 2,
          "title": "暗影五护法",
          "slug": "暗影五护法"
        },
        {
          "level": 3,
          "title": "远古异能兽",
          "slug": "远古异能兽"
        },
        {
          "level": 3,
          "title": "46号穷奇",
          "slug": "_46号穷奇"
        },
        {
          "level": 3,
          "title": "47号梼杌",
          "slug": "_47号梼杌"
        },
        {
          "level": 3,
          "title": "48号混沌",
          "slug": "_48号混沌"
        },
        {
          "level": 3,
          "title": "49号饕餮",
          "slug": "_49号饕餮"
        },
        {
          "level": 2,
          "title": "特种异能兽",
          "slug": "特种异能兽"
        },
        {
          "level": 3,
          "title": "变色魔龙兽",
          "slug": "变色魔龙兽"
        },
        {
          "level": 3,
          "title": "巨钳魔蝎兽",
          "slug": "巨钳魔蝎兽"
        },
        {
          "level": 3,
          "title": "毒角魔甲兽",
          "slug": "毒角魔甲兽"
        },
        {
          "level": 3,
          "title": "蟑螂兵团",
          "slug": "蟑螂兵团"
        },
        {
          "level": 2,
          "title": "终极异能兽",
          "slug": "终极异能兽"
        },
        {
          "level": 3,
          "title": "55号黑魔兽",
          "slug": "_55号黑魔兽"
        },
        {
          "level": 3,
          "title": "远古终极魔蜈兽",
          "slug": "远古终极魔蜈兽"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": "auto",
    "logo": "/assets/img/uestcimg.png",
    "search": false,
    "nav": [
      {
        "text": "主页面",
        "link": "/"
      },
      {
        "text": "导航栏",
        "link": "/detaildocs/guide/"
      },
      {
        "text": "剧情介绍",
        "link": "/detaildocs/plot/"
      },
      {
        "text": "人物及铠甲介绍",
        "link": "/detaildocs/char/"
      },
      {
        "text": "怪兽图鉴",
        "link": "/detaildocs/monster/"
      },
      {
        "text": "了解UESTC",
        "link": "https://www.uestc.edu.cn"
      }
    ]
  }
}